### ISSUE TITLE
Use new /dev/gpiomem interface

### ISSUE THREAD

**Issue by stevedesmond-ca** [stevedesmond-ca/SimpleGPIO#8]
The `sysfs` ABI is [deprecated](https://www.kernel.org/doc/Documentation/gpio/sysfs.txt), plus memory mapping would be way faster than writing to the filesystem.

**Comment by marknotgeorge** [comment]
I think the most straightforward way of doing this would be to make use of the [bcm2835](bcm2835 C library).

**Comment by stevedesmond-ca** [comment]
Thanks for the tip -- I'll check that out if I can't get it working with .NET's `MemoryMappedFile`

**Comment by stevedesmond-ca** [comment]
Superceded by the effort to move to `System.Device.Gpio` under the hood, since that will pick the best driver.
